### ISSUE TITLE
Getting error- Error: getaddrinfo ENOTFOUND undefined.service-now.com

### ISSUE THREAD

**Issue by gauravmudgal2002** [lvl0-io/snGet#2]
Hi Michael.

I am not much aware of node.js. Could you please advise me here.

While running your utility on node.js, I am getting the following error. 

C:\Users\HP\node_modules\snget>node app.js
Enter table: incident
Enter query: sys_id=a9f9958047543110a2851a8bd36d43b6
Error: Error: getaddrinfo ENOTFOUND undefined.service-now.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'undefined.service-now.com'
}
========================
Have updated env file as below:

## TARGET

TARGET_USERNAME="admin" #demo
TARGET_PASSWORD="****" #password1
TARGET_ENV="dev146420" #dev12345

## SOURCE

SOURCE_USERNAME="admin" #demo
SOURCE_PASSWORD="****" #password1
SOURCE_ENV="dev169771" #prod12345

**Comment by lvl0-io** [comment]
I need to update the instructions when you install it. 

If you move the snGet folder out of node_modules and run node snget/app.js

It should work. It's looking for dotenv. 

The other option is clone it from here. cd snget. npm i. And then node app.js.

**Comment by lvl0-io** [comment]
README has been updated along with an updated version on npm.  If you have any other issues feel free to post them here.  Thanks!

**Comment by gauravmudgal2002** [comment]
dotenv and snget is under the same folder node_modules. Pleaase refer image below.

![Capture](https://github.com/lvl0-io/snGet/assets/28958870/bf30383d-0b9b-431a-a52a-0acdb99e11df)

However I tried to move sn_get out of node_modules as you suggested. But still same error.

Please see below. Not sure if it is causing the issue.

C:\Users\HP>npm i snget

changed 1 package, and audited 3 packages in 3s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

C:\Users\HP>npm fund
HP
`-- https://github.com/motdotla/dotenv?sponsor=1
    `-- dotenv@16.3.1


C:\Users\HP>

**Comment by lvl0-io** [comment]
The first issue was "undefined" in the address, because it couldn't find / use dotenv and the .env file that contains the credentials and instance name.  If you are still getting undefined in the target address, its the folder structure that isn't right.  It might be easier to just clone it from GH instead.  Instructions have been updated in the README.

This is what it should look like: 
![image](https://github.com/lvl0-io/snGet/assets/106563820/68c40834-6925-4335-b89c-ef4a5f47d71e)

Note I get an error but that's because its not a valid instance, but it is calling the value from my .env file.
![image](https://github.com/lvl0-io/snGet/assets/106563820/9ca4bb16-a2a9-4b4e-8cc6-4dd406f135eb)

**Comment by lvl0-io** [comment]
@gauravmudgal2002 - I updated the README instructions using the ZIP file.  This is the easiest way to use this utility if one has limited knowledge of Git and Node.

Hope you got it working!  

Best,

MB

**Comment by gauravmudgal2002** [comment]
Hi Michael,

I tried with zip folder this time, but no luck. Still getting undefined.service-now.com error. I am attaching my folder here. Can you please have a look it? In case you find anything wrong, Please send me the rectified copy.

One good news, I created a copy of app.js. You will find it in my folder as app1.js. Here, I hardcoded all the env values and this worked perfectly fine.

Not sure why it is not picking the values from env file. :
[snget.zip](https://github.com/lvl0-io/snGet/files/12139687/snget.zip)

**Comment by lvl0-io** [comment]
I downloaded your ZIP file and found the problem.  See the screenshot below.  Your .env file appended .txt which is why it was not recognized.

![image](https://github.com/lvl0-io/snGet/assets/106563820/b2528af4-e6d3-4338-9a72-ebe1e1c55a71)

As soon as I removed that file extension so its just .env it worked as expected.

![image](https://github.com/lvl0-io/snGet/assets/106563820/6e21c85f-cb57-406c-9438-d4991054f019)

Attached is a working version without the values being hard coded in app.js

[snget.zip](https://github.com/lvl0-io/snGet/files/12139731/snget.zip)

Cheers!

**Comment by gauravmudgal2002** [comment]
Thanks You for your help!.

I just noticed .example in file name extension when I enable show 'File Name Extension' option in folder. I removed .example or .txt and it worked.
